POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 2,
  "memberId": "Mini",
  "name": "jung",
  "age" : 20
}

###
